version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - echo '{"name":"hello-world","imageUri":"REPOSITORY_URI"}' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
